### ISSUE TITLE
Fixing automatic build

### ISSUE THREAD

**Issue by svrooij** [svrooij/nodeftpd#2]
I should fix the automatic build

https://github.com/nodeftpd/nodeftpd/issues/128

**Comment by svrooij** [comment]
The current test suits is failing, Anyone got good ideas on how to proceed?

1. Setup auto build, only fail on eslint and continue on failed tests?
2. Setup auto build and continue no matter what?
3. Setup auto build and release a new version once the test succeed?

**Comment by svrooij** [comment]
I picked run lint and skip tests. But to continue with this library the tests should be fixed (and preferably converted to jest instead of mocha.

**Comment by svrooij** [comment]
@LolHens I've fixed the automatic build!

Every PR will be checked (but the tests failures are still ignored). At least now it releases automatically. Want to restart the development and maybe try to fix the failing tests?

**Comment by lhns** [comment]
Sure I will try!

**Comment by svrooij** [comment]
In the last run from the actions, you can see the results of my tries. Only 9 of 70 test fail.

Be sure to take the latest version because I changed a lot.

You can run the tests locally by running `npm run test-suites`
 https://github.com/svrooij/nodeftpd/runs/641207869?check_suite_focus=true
